name: Run Unittest
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - uses: fwilhe2/setup-kotlin@main
      - name: Run test
        run: |
          ./gradlew test
