name: Run Unittest
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.10
      - name: Run test
        run: |
          ./gradlew test
